---
- hosts: coreos
  become: yes
  become_method: sudo
  vars:
    docker_name: minecraft
    docker_image: itzg/minecraft-server
    docker_volume: /home/core/minecraft
    opts:
    - EULA=TRUE
    - JVM_OPTS=-Xmx1408M -Xms1408M
    systemd_service_path: /etc/systemd/system
  tasks:
  - name: install service
    template: src=minecraft.service.j2 dest={{ systemd_service_path }}/minecraft.service
  - service: name={{ systemd_service_path }}/minecraft.service enabled=yes
  - service: name=minecraft.service state=started